#!/usr/bin/env python3
"""KCL-to-dotfiles converter.
Reads generated/config.json (from KCL) and generates:
  - .dotter/global.toml
  - shared/env.toml
  - shared/completions.toml
  - packages-fedora.txt
  - Brewfile
"""

import json
import sys
from pathlib import Path

def _load_json():
    p = Path("generated/config.json")
    if not p.exists():
        print("ERROR: generated/config.json not found. Run `kcl run kcl/main.k` first.", file=sys.stderr)
        sys.exit(1)
    with open(p) as f:
        return json.load(f)


def _toml_escape_value(v):
    if isinstance(v, bool):
        return "true" if v else "false"
    if isinstance(v, (int, float)):
        return str(v)
    if isinstance(v, str):
        # Multiline strings: use triple-quotes
        if "\n" in v:
            return '"""' + v + '"""'
        # Escape quotes and backslashes
        if '"' in v or "\\" in v:
            v = v.replace("\\", "\\\\").replace('"', '\\"')
        return '"' + v + '"'
    if isinstance(v, list):
        items = [_toml_escape_value(i) for i in v]
        return "[" + ", ".join(items) + "]"
    return str(v)


def _write_dotter_toml(cfg, out_path):
    lines = []
    dotter = cfg["dotter"]

    def write_profile(name, profile):
        files = profile.get("files", {})
        variables = profile.get("variables", {})
        depends = profile.get("depends")

        if depends is not None:
            lines.append(f"[{name}]")
            lines.append(f'depends = {json.dumps(depends)}')
            lines.append("")

        if files:
            if depends is None:
                lines.append(f"[{name}.files]")
            else:
                lines.append(f"[{name}.files]")
            for k, v in files.items():
                key = json.dumps(k)  # handles special chars, spaces
                if isinstance(v, str):
                    lines.append(f'{key} = {json.dumps(v)}')
                elif isinstance(v, dict):
                    target = v.get("target", "")
                    t = v.get("type", "automatic")
                    if target:
                        lines.append(f'{key} = {{ target = {json.dumps(target)}, type = {json.dumps(t)} }}')
                    else:
                        lines.append(f'{key} = {{ type = {json.dumps(t)} }}')
            lines.append("")

        if variables:
            lines.append(f"[{name}.variables]")
            for k, v in variables.items():
                lines.append(f"{k} = {_toml_escape_value(v)}")
            lines.append("")

    write_profile("default", dotter["default"])
    write_profile("personal", dotter["personal"])
    write_profile("work", dotter["work"])
    write_profile("oda-mcp", dotter.get("oda_mcp", {}))

    # linux/mac profiles
    linux = dotter.get("linux", {})
    if linux.get("files") or linux.get("variables"):
        write_profile("linux", linux)

    mac = dotter.get("mac", {})
    if mac.get("files") or mac.get("variables"):
        write_profile("mac", mac)

    # themes
    for theme_name, theme_vars in dotter.get("themes", {}).items():
        lines.append(f"[{theme_name}.variables]")
        for k, v in theme_vars.items():
            lines.append(f"{k} = {_toml_escape_value(v)}")
        lines.append("")

    # settings
    settings = dotter.get("settings", {})
    if settings:
        lines.append("[settings]")
        for k, v in settings.items():
            lines.append(f"{k} = {_toml_escape_value(v)}")
        lines.append("")

    with open(out_path, "w") as f:
        f.write("\n".join(lines))
    print(f"  Wrote {out_path}")


def _write_env_toml(env, out_path):
    lines = ["# Generated by KCL — do not edit manually", ""]
    lines.append("[env]")

    # Core env vars
    if env.get("editor"):
        lines.append(f'EDITOR = "{env["editor"]}"')
    if env.get("xdg_config_home"):
        lines.append(f'XDG_CONFIG_HOME = "{env["xdg_config_home"]}"')
    if env.get("venv_home"):
        lines.append(f'VENV_HOME = "{env["venv_home"]}"')
    if env.get("nvm_dir"):
        lines.append(f'NVM_DIR = "{env["nvm_dir"]}"')
    if env.get("pnpm_home"):
        lines.append(f'PNPM_HOME = "{env["pnpm_home"]}"')
    if env.get("sf_use_generic_unix_keychain"):
        lines.append(f'SF_USE_GENERIC_UNIX_KEYCHAIN = "{env["sf_use_generic_unix_keychain"]}"')
    if env.get("sf_beta_track_file_moves"):
        lines.append(f'SF_BETA_TRACK_FILE_MOVES = "{env["sf_beta_track_file_moves"]}"')
    if env.get("lua_path"):
        lines.append(f'LUA_PATH = "{env["lua_path"]}"')
    if env.get("lua_cpath"):
        lines.append(f'LUA_CPATH = "{env["lua_cpath"]}"')

    # Profile-gated sections use dotter template variables
    lines.append("")
    lines.append("{{#if opencode_profile_work}}")
    lines.append("# GitLab configuration (work profile)")
    lines.append('GITLAB_URL = "{{gitlab_url}}"')
    lines.append("# NOTE: work credentials are injected from Proton Pass during dotter deploy.")
    lines.append("# They appear here because external CLI tools (glab, gh, nvim plugins) require")
    lines.append("# them as environment variables.")
    lines.append('GITLAB_TOKEN = ""')
    lines.append('SONAR_TOKEN = ""')
    lines.append('SLACK_TOKEN = ""')
    lines.append('SLACK_D_COOKIE = ""')
    lines.append("# Netskope CA certificates (work profile)")
    lines.append('NODE_EXTRA_CA_CERTS = "{{node_extra_ca_certs}}"')
    lines.append('REQUESTS_CA_BUNDLE = "{{node_extra_ca_certs}}"')
    lines.append("# Powerlevel10k (work profile)")
    lines.append('P10K_ROOT_DIR = "{{p10k_root_dir}}"')
    lines.append("{{/if}}")

    lines.append("")
    lines.append("{{#if opencode_profile_personal}}")
    lines.append("# Home Assistant")
    lines.append('HA_URL = "{{home_assistant_url}}"')
    lines.append("")
    lines.append("# Bluesky")
    lines.append('{{#if bluesky_handle}}BSKY_HANDLE = "{{bluesky_handle}}"')
    lines.append("{{/if}}")
    lines.append("# Plex")
    lines.append('PLEX_URL = "{{plex_url}}"')
    lines.append("")
    lines.append("# Proton Mail Bridge username")
    lines.append('{{#if proton_user}}PROTON_USER = "{{proton_user}}"')
    lines.append("{{/if}}")
    lines.append("{{/if}}")

    lines.append("")
    lines.append('{{#if tripit_username}}TRIPIT_USERNAME = "{{tripit_username}}"')
    lines.append("{{/if}}")

    lines.append("")
    lines.append("[path]")
    prepend = env.get("path_prepend", [])
    if prepend:
        lines.append("prepend = [")
        for p in prepend:
            lines.append(f'    {json.dumps(p)},')
        lines.append("]")

    append = env.get("path_append", [])
    if append:
        lines.append("append = [")
        for p in append:
            lines.append(f'    {json.dumps(p)},')
        lines.append("]")

    with open(out_path, "w") as f:
        f.write("\n".join(lines) + "\n")
    print(f"  Wrote {out_path}")


def _write_completions_toml(completions, out_path):
    lines = [
        "# Generated by KCL — do not edit manually",
        "# Shared completion definitions for zsh and nushell",
        "#",
        "# Usage:",
        "#   - zsh: parsed with a helper function, outputs to ~/.zsh/completion/_<tool>",
        "#   - nushell: parsed natively, outputs to ~/.cache/completions/<tool>.nu",
        "#",
        "# Each tool has:",
        "#   - zsh: command to generate zsh completions (piped to a file or sourced)",
        "#   - nu: command to generate nushell completions (piped to a cache file)",
        "#",
        "# Empty string means:",
        "#   - Handled by carapace bridge (nushell)",
        "#   - Handled by oh-my-zsh plugin (zsh)",
        "#   - Manual completions already exist",
        "#   - Tool doesn't support that shell",
        "#",
        "# Tools are automatically skipped if not found in PATH.",
        "",
    ]
    for tool_name, commands in completions.get("tools", {}).items():
        lines.append(f"[{tool_name}]")
        if commands.get("zsh"):
            lines.append(f'zsh = {json.dumps(commands["zsh"])}')
        if commands.get("nu"):
            lines.append(f'nu = {json.dumps(commands["nu"])}')
        lines.append("")

    with open(out_path, "w") as f:
        f.write("\n".join(lines) + "\n")
    print(f"  Wrote {out_path}")


def _write_packages_txt(packages, out_path):
    with open(out_path, "w") as f:
        for pkg in packages:
            f.write(pkg + "\n")
    print(f"  Wrote {out_path}")


def _write_brewfile(packages, out_path):
    lines = []
    for tap in packages.get("brew_taps", []):
        lines.append(f'tap "{tap}"')
    for formula in packages.get("brew_formulae", []):
        lines.append(f'brew "{formula}"')
    for cask in packages.get("brew_casks", []):
        lines.append(f'cask "{cask}"')
    for ext in packages.get("vscode_extensions", []):
        lines.append(f'vscode "{ext}"')

    with open(out_path, "w") as f:
        f.write("\n".join(lines) + "\n")
    print(f"  Wrote {out_path}")


def main():
    cfg = _load_json()
    dotter = cfg["dotter"]
    env = cfg["env"]
    completions = cfg["completions"]
    packages = dotter["packages"]

    # Ensure output dirs
    Path(".dotter").mkdir(exist_ok=True)
    Path("shared").mkdir(exist_ok=True)

    print("Generating dotfiles from KCL config...")
    _write_dotter_toml(cfg, ".dotter/global.toml")
    _write_env_toml(env, "shared/env.toml")
    _write_completions_toml(completions, "shared/completions.toml")
    _write_packages_txt(packages.get("fedora", []), "packages-fedora.txt")
    _write_brewfile(packages, "Brewfile")
    print("Done.")


if __name__ == "__main__":
    main()
