#!/usr/bin/env python3
"""KCL-to-dotfiles converter.

Reads out/config.json (from KCL) and generates TOML/text config files.
Text files (ghostty, gitconfig, pnpm/rc, tmux.conf) are now written
    directly by KCL via file.write(). This script only handles:
- dotter global.toml (custom format)
- TOML files (via tomli_w)
- Template TOML files (with Handlebars marker resolution)
- env.toml (custom format with Handlebars conditionals)
- completions.toml (custom format)
- packages (txt and Brewfile)
"""

import io
import json
import sys
from pathlib import Path

OUT_DIR = Path("out")
META_DIR = OUT_DIR  # Metadata files are alongside output

try:
    import tomli_w
except ImportError:
    print("ERROR: 'tomli_w' module not found. Install it with:", file=sys.stderr)
    print("  pip3 install tomli_w", file=sys.stderr)
    print("  uv pip install tomli_w", file=sys.stderr)
    sys.exit(1)


def _load_json(path):
    p = Path(path)
    if not p.exists():
        print(f"ERROR: {path} not found. Run `kcl run src/main.k` first.", file=sys.stderr)
        sys.exit(1)
    with open(p) as f:
        return json.load(f)


def _is_template_marker(value):
    """Check if a value is a template marker dict like {TEMPLATE_MARKER: 'field'}."""
    return isinstance(value, dict) and "TEMPLATE_MARKER" in value and len(value) == 1


def _resolve_template_value(value):
    """Replace template marker dicts with Handlebars placeholders."""
    if _is_template_marker(value):
        return f"{{{{{value['TEMPLATE_MARKER']}}}}}"
    elif isinstance(value, dict):
        return {k: _resolve_template_value(v) for k, v in value.items()}
    elif isinstance(value, list):
        return [_resolve_template_value(item) for item in value]
    return value


def _write_raw_text(content, out_path, *, strip_trailing_newline=False):
    """Write raw text content verbatim."""
    out_path.parent.mkdir(parents=True, exist_ok=True)
    if strip_trailing_newline:
        content = content.rstrip("\n")
    with open(out_path, "w") as f:
        f.write(content)
    print(f"  Wrote {out_path}")


def _write_toml(data, out_path, *, header=None, template=False):
    """Write a dict as TOML using tomli_w."""
    out_path.parent.mkdir(parents=True, exist_ok=True)

    if template:
        data = _resolve_template_value(data)

    if not isinstance(data, dict):
        raise TypeError(f"TOML writer expects dict, got {type(data).__name__}")

    buf = io.BytesIO()
    tomli_w.dump(data, buf)
    raw = buf.getvalue().decode("utf-8")

    lines = ["# Generated by KCL — do not edit manually", ""]
    if header:
        lines.append(header)
        lines.append("")
    lines.append(raw)

    with open(out_path, "w") as f:
        f.write("\n".join(lines))
    print(f"  Wrote {out_path}")


def _write_env_toml(env_meta):
    """Write the env.toml file with Handlebars conditionals."""
    out_path = OUT_DIR / env_meta["path"]
    out_path.parent.mkdir(parents=True, exist_ok=True)

    core_env = env_meta.get("core_vars", {})
    sections = env_meta.get("sections", [])
    path_prepend = env_meta.get("path_prepend", [])
    path_append = env_meta.get("path_append", [])

    lines = ["# Generated by KCL — do not edit manually", ""]
    lines.append("[env]")

    # Core env vars — filter metadata and path sections
    skip = ("_", "profile_work", "profile_personal", "path_prepend", "path_append", "sections", "editor")
    for key, val in sorted(core_env.items()):
        if key.startswith("_") or key in skip:
            continue
        if val:
            lines.append(f'{key.upper()} = "{val}"')

    # Profile-gated sections
    for section in sections:
        condition = section.get("condition", "")
        vars_dict = section.get("vars", {})

        if condition:
            lines.append("")
            lines.append(condition)

        for var_name, template_field in vars_dict.items():
            if template_field:
                if template_field in ("bluesky_handle", "proton_user"):
                    lines.append(f"{{{{#if {template_field}}}}}" + f'{var_name} = "{{{{{template_field}}}}}"')
                    lines.append("{{/if}}")
                else:
                    lines.append(f'{var_name} = "{{{{{template_field}}}}}"')
            else:
                lines.append(f'{var_name} = ""')

        if condition:
            lines.append("{{/if}}")

    # TripIt conditional
    lines.append("")
    lines.append('{{#if tripit_username}}TRIPIT_USERNAME = "{{tripit_username}}"')
    lines.append("{{/if}}")

    # Path sections
    lines.append("")
    lines.append("[path]")
    if path_prepend:
        lines.append("prepend = [")
        for p in path_prepend:
            lines.append(f'    {json.dumps(p)},')
        lines.append("]")
    if path_append:
        lines.append("append = [")
        for p in path_append:
            lines.append(f'    {json.dumps(p)},')
        lines.append("]")

    with open(out_path, "w") as f:
        f.write("\n".join(lines) + "\n")
    print(f"  Wrote {out_path}")


def _write_completions_toml(completions_meta):
    """Write completions.toml."""
    out_path = OUT_DIR / completions_meta["path"]
    out_path.parent.mkdir(parents=True, exist_ok=True)
    data = completions_meta["data"]
    header = (
        "# Generated by KCL — do not edit manual\n"
        "# Shared completion definitions for zsh and nushell\n"
        "#\n"
        "# Usage:\n"
        "#   - zsh: parsed with a helper function, outputs to ~/.zsh/completion/_<tool>\n"
        "#   - nushell: parsed natively, outputs to ~/.cache/completions/<tool>.nu\n"
        "#\n"
        "# Each tool has:\n"
        "#   - zsh: command to generate zsh completions (piped to a file or sourced)\n"
        "#   - nu: command to generate nushell completions (piped to a cache file)\n"
        "#\n"
        "# Empty string means:\n"
        "#   - Handled by carapace bridge (nushell)\n"
        "#   - Handled by oh-my-zsh plugin (zsh)\n"
        "#   - Manual completions already exist\n"
        "#   - Tool doesn't support that shell\n"
        "#\n"
        "# Tools are automatically skipped if not found in PATH.\n"
    )
    lines = [header]
    for tool_name, commands in data.get("tools", {}).items():
        lines.append(f"[{tool_name}]")
        if commands.get("zsh"):
            lines.append(f'zsh = {json.dumps(commands["zsh"])}')
        if commands.get("nu"):
            lines.append(f'nu = {json.dumps(commands["nu"])}')
        lines.append("")

    with open(out_path, "w") as f:
        f.write("\n".join(lines) + "\n")
    print(f"  Wrote {out_path}")


def _write_dotter_toml(cfg, out_path):
    """Write dotter global.toml."""
    lines = []
    dotter = cfg["dotter"]

    def _escape_toml_value(v):
        if isinstance(v, bool):
            return "true" if v else "false"
        if isinstance(v, (int, float)):
            return str(v)
        if isinstance(v, str):
            if "\n" in v:
                return '"""' + v + '"""'
            escaped = v.replace("\\", "\\\\").replace('"', '\\"')
            return f'"{escaped}"'
        return json.dumps(v)

    def write_profile(name, profile):
        files = profile.get("files", {})
        variables = profile.get("variables", {})
        depends = profile.get("depends")

        if depends is not None:
            lines.append(f"[{name}]")
            lines.append(f"depends = {json.dumps(depends)}")
            lines.append("")

        if files:
            lines.append(f"[{name}.files]")
            for k, v in files.items():
                key = json.dumps(k)
                if isinstance(v, str):
                    lines.append(f"{key} = {json.dumps(v)}")
                elif isinstance(v, dict):
                    target = v.get("target", "")
                    t = v.get("type", "automatic")
                    if target:
                        lines.append(f"{key} = {{ target = {json.dumps(target)}, type = {json.dumps(t)} }}")
                    else:
                        lines.append(f"{key} = {{ type = {json.dumps(t)} }}")
            lines.append("")

        if variables:
            lines.append(f"[{name}.variables]")
            for k, v in variables.items():
                lines.append(f"{k} = {_escape_toml_value(v)}")
            lines.append("")

    write_profile("default", dotter["default"])
    write_profile("personal", dotter["personal"])
    write_profile("work", dotter["work"])
    write_profile("oda-mcp", dotter.get("oda_mcp", {}))

    linux = dotter.get("linux", {})
    if linux.get("files") or linux.get("variables"):
        write_profile("linux", linux)

    mac = dotter.get("mac", {})
    if mac.get("files") or mac.get("variables"):
        write_profile("mac", mac)

    for theme_name, theme_vars in dotter.get("themes", {}).items():
        lines.append(f"[{theme_name}.variables]")
        for k, v in theme_vars.items():
            lines.append(f"{k} = {_escape_toml_value(v)}")
        lines.append("")

    settings = dotter.get("settings", {})
    if settings:
        lines.append("[settings]")
        for k, v in settings.items():
            lines.append(f"{k} = {_escape_toml_value(v)}")
        lines.append("")
    else:
        lines.append("[settings]")
    # Add pre_deploy hook to ensure KCL generation runs before dotter reads files
    lines.append('pre_deploy = ".dotter/pre_deploy.sh"')
    lines.append("")

    with open(out_path, "w") as f:
        f.write("\n".join(lines))
    print(f"  Wrote {out_path}")


def _write_packages_txt(packages, out_path):
    with open(out_path, "w") as f:
        for pkg in packages:
            f.write(pkg + "\n")
    print(f"  Wrote {out_path}")


def _write_brewfile(data, out_path):
    lines = []
    for tap in data.get("brew_taps", []):
        lines.append(f'tap "{tap}"')
    for formula in data.get("brew_formulae", []):
        lines.append(f'brew "{formula}"')
    for cask in data.get("brew_casks", []):
        lines.append(f'cask "{cask}"')
    for ext in data.get("vscode_extensions", []):
        lines.append(f'vscode "{ext}"')

    with open(out_path, "w") as f:
        f.write("\n".join(lines) + "\n")
    print(f"  Wrote {out_path}")


def main():
    cfg = _load_json("out/config.json")

    print("Generating dotfiles from KCL config...")

    # 1. dotter global.toml
    _write_dotter_toml(cfg, Path(".dotter/global.toml"))

    # 2. TOML files (direct serialization from KCL data)
    toml_map = {
        "atuin/config.toml": (cfg.get("atuin", {}), "# Atuin config — generated by KCL"),
        "starship.toml": (cfg.get("starship", {}), "# Starship config — generated by KCL"),
        "aerospace.toml": (cfg.get("aerospace", {}), "# Aerospace config — generated by KCL"),
        "iamb/config.toml": (cfg.get("iamb", {}), "# iamb config — generated by KCL"),
        "gitlogue/config.toml": (cfg.get("gitlogue", {}), "# gitlogue config — generated by KCL"),
    }
    for path, (data, header) in toml_map.items():
        if data:
            _write_toml(data, OUT_DIR / path, header=header)

    # 3. Template TOML files (with Handlebars marker resolution)
    templates = cfg.get("templates", {})
    if templates.get("jj"):
        _write_toml(templates["jj"], OUT_DIR / "jj/config.toml",
                    header="# jj config — generated by KCL", template=True)

    # 4. Special: env.toml (from metadata)
    env_meta = _load_json("out/.env_meta.json")
    _write_env_toml(env_meta)

    # 5. Special: completions.toml (from metadata)
    completions_meta = _load_json("out/.completions_meta.json")
    _write_completions_toml(completions_meta)

    # 6. Special: packages (from metadata)
    packages_meta = _load_json("out/.packages_meta.json")
    fedora = packages_meta.get("fedora_txt", {})
    if fedora.get("lines"):
        _write_packages_txt(fedora["lines"], OUT_DIR / fedora["path"])

    brew = packages_meta.get("brewfile", {})
    if brew.get("data"):
        _write_brewfile(brew["data"], OUT_DIR / brew["path"])

    # 7. JSONC files (text with JSON + header comment)
    if cfg.get("opencode"):
        _write_raw_text(cfg["opencode"], OUT_DIR / "opencode.jsonc")

    print("Done.")


if __name__ == "__main__":
    main()
