#!/usr/bin/env python3
"""
Patch OpenCode opencode.jsonc with secrets from the environment (Proton Pass).

Reads the deployed JSONC file, replaces placeholder tokens with actual values,
and writes it back. The file may contain comments (stripped before JSON parse).

Usage:
    patch_opencode_secrets.py ~/.config/opencode/opencode.jsonc \
        --github-token ghp_xxx \
        --ha-token eyJhbGci... \
        --obsidian-token abc123
"""

import argparse
import json
import re
import sys


def strip_jsonc_comments(text: str) -> str:
    """Remove C-style and line comments from JSONC text."""
    # Remove single-line comments
    text = re.sub(r'//.*$', '', text, flags=re.MULTILINE)
    # Remove multi-line comments
    text = re.sub(r'/\*.*?\*/', '', text, flags=re.DOTALL)
    return text


def main() -> int:
    parser = argparse.ArgumentParser(description="Patch OpenCode secrets into JSONC config")
    parser.add_argument("config_path", help="Path to opencode.jsonc")
    parser.add_argument("--github-token", default="", help="GitHub PAT to inject into GitHub MCP env")
    parser.add_argument("--ha-token", default="", help="Home Assistant token to inject into HA MCP headers")
    parser.add_argument("--gitlab-token", default="", help="GitLab PAT to inject into GitLab MCP env")
    parser.add_argument("--postman-token", default="", help="Postman API key to inject into Postman MCP headers")
    parser.add_argument("--sonar-token", default="", help="SonarQube token to inject into SonarQube MCP env")
    args = parser.parse_args()

    path = args.config_path
    try:
        with open(path, "r", encoding="utf-8") as f:
            raw = f.read()
    except FileNotFoundError:
        print(f"ERROR: Config not found: {path}", file=sys.stderr)
        return 1

    cleaned = strip_jsonc_comments(raw)
    try:
        cfg = json.loads(cleaned)
    except json.JSONDecodeError as e:
        print(f"ERROR: Failed to parse JSONC: {e}", file=sys.stderr)
        return 1

    modified = False

    # --- GitHub MCP: inject env token ---
    if args.github_token:
        mcp = cfg.get("mcp", {})
        gh = mcp.get("GitHub")
        if gh and isinstance(gh, dict):
            env = gh.setdefault("environment", {})
            env["GITHUB_PERSONAL_ACCESS_TOKEN"] = args.github_token
            env.setdefault("PATH", "/usr/bin:/bin:/usr/sbin:/sbin")
            modified = True
            print("  Patched GitHub MCP token")

    # --- GitLab MCP: inject env token ---
    if args.gitlab_token:
        mcp = cfg.get("mcp", {})
        gl = mcp.get("GitLab")
        if gl and isinstance(gl, dict):
            env = gl.setdefault("environment", {})
            env["GITLAB_PERSONAL_ACCESS_TOKEN"] = args.gitlab_token
            env.setdefault("PATH", "/usr/bin:/bin:/usr/sbin:/sbin")
            modified = True
            print("  Patched GitLab MCP token")

    # --- Postman MCP: inject header token ---
    if args.postman_token:
        mcp = cfg.get("mcp", {})
        pm = mcp.get("Postman")
        if pm and isinstance(pm, dict):
            headers = pm.setdefault("headers", {})
            headers["Authorization"] = f"Bearer {args.postman_token}"
            modified = True
            print("  Patched Postman MCP token")

    # --- SonarQube MCP: inject env token ---
    if args.sonar_token:
        mcp = cfg.get("mcp", {})
        sq = mcp.get("SonarQube")
        if sq and isinstance(sq, dict):
            env = sq.setdefault("environment", {})
            env["SONARQUBE_TOKEN"] = args.sonar_token
            modified = True
            print("  Patched SonarQube MCP token")

    # --- Home Assistant MCP: inject header token ---
    if args.ha_token:
        mcp = cfg.get("mcp", {})
        ha = mcp.get("Home Assistant")
        if ha and isinstance(ha, dict):
            headers = ha.setdefault("headers", {})
            headers["Authorization"] = f"Bearer {args.ha_token}"
            modified = True
            print("  Patched Home Assistant MCP token")

    # --- Obsidian MCP: inject header token ---
    if args.obsidian_token:
        mcp = cfg.get("mcp", {})
        obs = mcp.get("Obsidian")
        if obs and isinstance(obs, dict):
            headers = obs.setdefault("headers", {})
            headers["Authorization"] = f"Bearer {args.obsidian_token}"
            modified = True
            print("  Patched Obsidian MCP token")

    if not modified:
        print("  Nothing to patch (no matching MCP servers found)")
        return 0

    # Write back — preserve original comments by rewriting only the JSON portion
    # (simple approach: re-serialize; comments are lost. For comment preservation
    # we'd need a full JSONC parser/writer; opencode.jsonc is auto-generated by
    # dotter from Handlebars templates so comments are static and can be regenerated.)
    with open(path, "w", encoding="utf-8") as f:
        json.dump(cfg, f, indent=2)
        f.write("\n")

    print("  Config saved.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
